import { type NextPage } from "next";
import Head from "next/head";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rent A Dev</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen bg-[conic-gradient(at_bottom,_var(--tw-gradient-stops))] from-slate-300 via-violet-500 to-rose-800">
        hola
      </main>
    </>
  );
};

export default SinglePostPage;
